# Generated by Django 6.0 on 2026-02-11 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('role', models.CharField(choices=[('admin', 'مدير'), ('doc', 'طبيب'), ('patient', 'مريض')], default='patient', max_length=10, verbose_name='الدور')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='الصورة الشخصية')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
