# Generated by Django 6.0 on 2026-02-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Primary Configuration', max_length=100, verbose_name='اسم الإعداد')),
                ('email_host', models.CharField(max_length=255, verbose_name='خادم البريد (SMTP Host)')),
                ('email_port', models.IntegerField(default=587, verbose_name='المنفذ (Port)')),
                ('email_host_user', models.CharField(max_length=255, verbose_name='اسم المستخدم')),
                ('email_host_password', models.CharField(max_length=255, verbose_name='كلمة المرور')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='استخدام TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='استخدام SSL')),
                ('default_from_email', models.EmailField(max_length=254, verbose_name='البريد المرسل الافتراضي')),
                ('is_active', models.BooleanField(default=False, verbose_name='تفعيل')),
            ],
            options={
                'verbose_name': 'إعدادات البريد الإلكتروني',
                'verbose_name_plural': 'إعدادات البريد الإلكتروني',
            },
        ),
    ]
