# Generated by Django 6.0 on 2026-02-24 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdultMedicalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="الاسم الكامل",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="العمر"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "ذكر"), ("female", "أنثى")],
                        max_length=10,
                        null=True,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "aphasie",
                    models.BooleanField(default=False, verbose_name="الحبسة الكلامية"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حالة طبية (بالغ)",
                "verbose_name_plural": "حالات طبية (بالغين)",
            },
        ),
        migrations.CreateModel(
            name="ChildMedicalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="الاسم الكامل",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="العمر"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "ذكر"), ("female", "أنثى")],
                        max_length=10,
                        null=True,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "aphasie",
                    models.BooleanField(default=False, verbose_name="الحبسة الكلامية"),
                ),
                (
                    "disorders",
                    models.TextField(
                        blank=True, null=True, verbose_name="الاضطرابات (مفصولة بفاصلة)"
                    ),
                ),
                (
                    "syndromes",
                    models.TextField(
                        blank=True, null=True, verbose_name="المتلازمات (مفصولة بفاصلة)"
                    ),
                ),
                (
                    "intellectual_disability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weak", "ضعيف"),
                            ("middle", "متوسط"),
                            ("hard", "شديد"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="الإعاقة الذهنية",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حالة طبية (طفل)",
                "verbose_name_plural": "حالات طبية (أطفال)",
            },
        ),
        migrations.CreateModel(
            name="ElderlyMedicalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="الاسم الكامل",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="العمر"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "ذكر"), ("female", "أنثى")],
                        max_length=10,
                        null=True,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "aphasie",
                    models.BooleanField(default=False, verbose_name="الحبسة الكلامية"),
                ),
                (
                    "alzheimer",
                    models.BooleanField(default=False, verbose_name="ألزهايمر"),
                ),
                (
                    "parkinson",
                    models.BooleanField(default=False, verbose_name="باركنسون"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حالة طبية (مسن)",
                "verbose_name_plural": "حالات طبية (مسنين)",
            },
        ),
    ]
