# Generated by Django 6.0 on 2026-02-26 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_medicalcase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الدورة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (د.ج)')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='اسم المعلم')),
                ('description', models.TextField(verbose_name='وصف الدورة')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='الوسوم (مفصولة بفاصلة)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='صورة الغلاف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'دورة تعليمية',
                'verbose_name_plural': 'الدورات التعليمية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة التسجيل')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبول')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='تم القبول بواسطة')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='dashboard.course', verbose_name='الدورة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تسجيل في دورة',
                'verbose_name_plural': 'التسجيلات في الدورات',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(upload_to='payments/receipts/%Y/%m/', verbose_name='صورة الإيصال')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='dashboard.courseenrollment', verbose_name='التسجيل')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
            ],
            options={
                'verbose_name': 'دفع',
                'verbose_name_plural': 'المدفوعات',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الفيديو')),
                ('description', models.TextField(blank=True, verbose_name='وصف الفيديو')),
                ('video_file', models.FileField(upload_to='courses/videos/', verbose_name='ملف الفيديو')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='المدة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_free', models.BooleanField(default=False, verbose_name='مجاني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.course', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'فيديو',
                'verbose_name_plural': 'الفيديوهات',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
