# Generated by Django 6.0 on 2026-03-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_payment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultmedicalcase',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AddField(
            model_name='childmedicalcase',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AddField(
            model_name='elderlymedicalcase',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
    ]
