# Generated by Django 6.0 on 2026-04-18 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_adultmedicalcase_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المقال')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='الرابط المختصر')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('category', models.CharField(choices=[('before_birth', 'قبل الولادة'), ('during_birth', 'أثناء الولادة'), ('after_birth', 'بعد الولادة')], max_length=20, verbose_name='الفئة')),
                ('tags', models.CharField(blank=True, help_text='لأغراض SEO', max_length=500, verbose_name='الوسوم (مفصولة بفاصلة)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/', verbose_name='صورة الغلاف')),
                ('is_published', models.BooleanField(default=False, verbose_name='تم النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
