# Generated by Django 6.0 on 2026-04-22 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان اللعبة')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='الرابط المختصر')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (د.ج)')),
                ('description', models.TextField(verbose_name='وصف اللعبة')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='الوسوم (مفصولة بفاصلة)')),
                ('thumbnail', models.ImageField(upload_to='games/thumbnails/', verbose_name='صورة الغلاف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'لعبة',
                'verbose_name_plural': 'الألعاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games/gallery/', verbose_name='الصورة')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.game', verbose_name='اللعبة')),
            ],
            options={
                'verbose_name': 'صورة اللعبة',
                'verbose_name_plural': 'صور الألعاب',
            },
        ),
        migrations.CreateModel(
            name='GameOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('wilaya', models.CharField(max_length=100, verbose_name='الولاية')),
                ('commune', models.CharField(max_length=100, verbose_name='البلدية')),
                ('address', models.TextField(verbose_name='العنوان بالتفصيل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.game', verbose_name='اللعبة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم (اختياري)')),
            ],
            options={
                'verbose_name': 'طلب لعبة',
                'verbose_name_plural': 'طلبات الألعاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
